#!/bin/sh

#  systemupdate.sh
#
#
#  Created by Cyrus on 2/24/13.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
#  SYNOPSIS:
#  This script simply updates the system.
#

echo
echo "Beginning system update..."
echo
sudo apt-get update -y
sudo apt-get dist-upgrade -y
sudo rpi-update
echo
echo
echo "Cleaning up..."
echo
sudo apt-get autoremove
./package_cleanup.sh
exit $?
