
ARDUINO_DIR  = /Applications/Arduino.app

TARGET       = Raspi_ATX_PMU
ARDUINO_LIBS =  ~/Projects/CyrusBuiltHTPC/Arduino/Raspi_ATX_PMU/lib

BOARD_TAG    = Uno
ARDUINO_PORT = /dev/ttyUSB0


include $(ARDUINO_DIR)/Arduino.mk


